/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function horizontalBrowseTransportReset(): void
export declare function horizontalBrowseTransportSetDeckState(deck: string, nowMs: number | undefined | null, payload: HorizontalBrowseTransportDeckInput): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportSetState(payload: HorizontalBrowseTransportStateInput): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportSetBeatGrid(deck: string, nowMs: number | undefined | null, payload: HorizontalBrowseTransportBeatGridInput): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportSetSyncEnabled(deck: string, nowMs: number | undefined | null, enabled: boolean): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportBeatsync(deck: string, nowMs?: number | undefined | null): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportSetLeader(deck?: string | undefined | null, nowMs?: number | undefined | null): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportSetPlaying(deck: string, nowMs: number, playing: boolean): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportSeek(deck: string, nowMs: number, currentSec: number): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportSetMetronome(deck: string, enabled: boolean, volumeLevel: number): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportToggleLoop(deck: string, nowMs: number): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportStepLoopBeats(deck: string, nowMs: number, direction: number): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportSetLoopFromRange(deck: string, startSec: number, endSec: number): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportClearLoop(deck: string): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportSetGain(deck: string, gain: number): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportSetOutputState(crossfaderValue: number, masterGain: number): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportSnapshot(nowMs?: number | undefined | null): HorizontalBrowseTransportSnapshot
export declare function horizontalBrowseTransportVisualizerSnapshot(): HorizontalBrowseTransportVisualizerSnapshot
export interface HorizontalBrowseTransportDeckInput {
  filePath?: string
  title?: string
  bpm?: number
  firstBeatMs?: number
  barBeatOffset?: number
  timeBasisOffsetMs?: number
  durationSec: number
  currentSec: number
  lastObservedAtMs: number
  playing: boolean
  playbackRate: number
  masterTempoEnabled: boolean
}
export interface HorizontalBrowseTransportBeatGridInput {
  filePath?: string
  bpm?: number
  firstBeatMs?: number
  barBeatOffset?: number
  timeBasisOffsetMs?: number
}
export interface HorizontalBrowseTransportStateInput {
  nowMs?: number
  top: HorizontalBrowseTransportDeckInput
  bottom: HorizontalBrowseTransportDeckInput
}
export interface HorizontalBrowseTransportDeckSnapshot {
  deck: string
  label: string
  loaded: boolean
  decoding: boolean
  playing: boolean
  currentSec: number
  durationSec: number
  playbackRate: number
  masterTempoEnabled: boolean
  bpm: number
  effectiveBpm: number
  renderCurrentSec: number
  syncEnabled: boolean
  syncLock: string
  leader: boolean
  loopActive: boolean
  loopBeatValue: number
  loopStartBeatIndex?: number
  loopStartSec: number
  loopEndSec: number
}
export interface HorizontalBrowseTransportOutputSnapshot {
  crossfaderValue: number
  masterGain: number
  topDeckGain: number
  bottomDeckGain: number
}
export interface HorizontalBrowseTransportSnapshot {
  leaderDeck?: string
  top: HorizontalBrowseTransportDeckSnapshot
  bottom: HorizontalBrowseTransportDeckSnapshot
  output: HorizontalBrowseTransportOutputSnapshot
}
export interface HorizontalBrowseTransportVisualizerSnapshot {
  timeDomainData: Array<number>
}
export interface MixxxWaveformBand {
  left: Buffer
  right: Buffer
  peakLeft: Buffer
  peakRight: Buffer
}
export interface MixxxWaveformBands {
  low: MixxxWaveformBand
  mid: MixxxWaveformBand
  high: MixxxWaveformBand
  all: MixxxWaveformBand
}
export interface MixxxWaveformData {
  duration: number
  sampleRate: number
  step: number
  bands: MixxxWaveformBands
}
export interface PioneerHotCueRecord {
  slot: number
  label: string
  timeSec: number
  isLoop: boolean
  loopTimeSec?: number
  comment?: string
  colorIndex?: number
  colorName?: string
  colorHex?: string
  source?: string
}
export interface PioneerMemoryCueRecord {
  timeSec: number
  isLoop: boolean
  loopTimeSec?: number
  order: number
  comment?: string
  colorIndex?: number
  colorName?: string
  colorHex?: string
  source?: string
}
export interface PioneerCueDump {
  analyzeFilePath: string
  cueFilePath: string
  hotCues: Array<PioneerHotCueRecord>
  memoryCues: Array<PioneerMemoryCueRecord>
  error?: string
}
export declare function readPioneerCues(analyzeFilePath: string): PioneerCueDump
/** 进度信息结构体 */
export interface ProcessProgress {
  processed: number
  total: number
}
/** 音频文件处理结果 */
export interface AudioFileResult {
  /** 整个文件的 SHA256（当前为标准化 PCM 内容哈希），用于去重 */
  sha256Hash: string
  /** 原始文件路径 */
  filePath: string
  /** 错误描述（当分析失败时） */
  error?: string
}
/** 音频解码结果 */
export interface DecodeAudioResult {
  /** PCM 数据（Buffer，内部为 f32 小端序，需在 JS 侧转为 Float32Array） */
  pcmData: Buffer
  /** 采样率 */
  sampleRate: number
  /** 声道数 */
  channels: number
  /** 总帧数 */
  totalFrames: number
  /** 解码后端（symphonia / ffmpeg / ffmpeg-fallback） */
  decoderBackend?: string
  /** 错误描述（当解码失败时） */
  error?: string
}
/** SoundTouch 处理结果 */
export interface SoundTouchProcessResult {
  /** PCM 数据（Buffer，内部为 f32 小端序） */
  pcmData: Buffer
  /** 采样率 */
  sampleRate: number
  /** 声道数 */
  channels: number
  /** 总帧数 */
  totalFrames: number
  /** 错误描述（失败时） */
  error?: string
}
/** 调性分析结果 */
export interface KeyAnalysisResult {
  /** ID3v2 ASCII key 文本 */
  keyText: string
  /** 错误描述（当分析失败时） */
  error?: string
}
/** 调性+BPM分析结果 */
export interface KeyBpmAnalysisResult {
  /** ID3v2 ASCII key 文本 */
  keyText: string
  /** BPM 值 */
  bpm: number
  /** 首拍偏移（毫秒） */
  firstBeatMs: number
  /** 调性分析错误描述 */
  keyError?: string
  /** BPM 分析错误描述 */
  bpmError?: string
}
/** Pioneer 旧 Device Library 调试输出 */
export interface PioneerExportDebugDump {
  /** export.pdb 路径 */
  exportPdbPath: string
  /** 表摘要 */
  tableSummaries: Array<string>
  /** 以树形文本打印的播放列表结构 */
  playlistTreeLines: Array<string>
  /** 播放列表树原始行总数 */
  playlistTreeTotal: number
  /** 播放列表项原始行总数 */
  playlistEntryTotal: number
  /** 曲目原始行总数 */
  trackTotal: number
  /** 播放列表项调试文本 */
  playlistEntries: Array<string>
  /** 曲目调试文本 */
  tracks: Array<string>
  /** 错误描述（失败时） */
  error?: string
}
/** Pioneer 播放列表树节点 */
export interface PioneerPlaylistTreeNodeRecord {
  /** 节点 ID */
  id: number
  /** 父节点 ID（根为 0） */
  parentId: number
  /** 节点名称 */
  name: string
  /** 是否为文件夹 */
  isFolder: boolean
  /** 读取顺序，用于前端稳定排序 */
  order: number
}
/** Pioneer 播放列表树读取结果 */
export interface PioneerPlaylistTreeDump {
  /** export.pdb 路径 */
  exportPdbPath: string
  /** 节点总数 */
  nodeTotal: number
  /** 文件夹节点数 */
  folderTotal: number
  /** 歌单节点数 */
  playlistTotal: number
  /** 播放列表树节点 */
  nodes: Array<PioneerPlaylistTreeNodeRecord>
  /** 错误描述（失败时） */
  error?: string
}
/** Pioneer 歌单曲目记录 */
export interface PioneerPlaylistTrackRecord {
  /** 播放列表 ID */
  playlistId: number
  /** 曲目 ID */
  trackId: number
  /** 原始 entry_index */
  entryIndex: number
  /** 曲目标题 */
  title: string
  /** 文件名 */
  fileName: string
  /** 文件路径 */
  filePath: string
  /** 艺术家 */
  artist: string
  /** 专辑 */
  album: string
  /** 厂牌 */
  label: string
  /** 流派 */
  genre: string
  /** 调性文本 */
  keyText: string
  /** BPM */
  bpm: number
  /** 时长（秒） */
  durationSec: number
  /** 比特率 */
  bitrate: number
  /** 采样率 */
  sampleRate: number
  /** 采样位深 */
  sampleDepth: number
  /** 音轨号 */
  trackNumber: number
  /** 碟号 */
  discNumber: number
  /** 年份 */
  year: number
  /** 分析文件路径 */
  analyzePath: string
  /** 评论 */
  comment: string
  /** 导入日期 */
  dateAdded: string
  /** 封面 Artwork ID */
  artworkId: number
  /** 封面路径（相对 U 盘根目录的 Pioneer 路径） */
  artworkPath: string
}
/** Pioneer 单歌单曲目读取结果 */
export interface PioneerPlaylistTrackDump {
  /** export.pdb 路径 */
  exportPdbPath: string
  /** 播放列表 ID */
  playlistId: number
  /** 播放列表名称 */
  playlistName: string
  /** 曲目总数 */
  trackTotal: number
  /** 曲目列表 */
  tracks: Array<PioneerPlaylistTrackRecord>
  /** 错误描述（失败时） */
  error?: string
}
/** Pioneer 预览波形单列 */
export interface PioneerPreviewWaveformColumn {
  /** 背景层高度 */
  backHeight: number
  /** 前景层高度 */
  frontHeight: number
  /** 背景层颜色 R */
  backColorR: number
  /** 背景层颜色 G */
  backColorG: number
  /** 背景层颜色 B */
  backColorB: number
  /** 前景层颜色 R */
  frontColorR: number
  /** 前景层颜色 G */
  frontColorG: number
  /** 前景层颜色 B */
  frontColorB: number
}
/** Pioneer 预览波形读取结果 */
export interface PioneerPreviewWaveformDump {
  /** export.pdb 里记录的分析文件路径 */
  analyzeFilePath: string
  /** 实际读取的预览文件路径 */
  previewFilePath: string
  /** 波形样式（blue / rgb） */
  style: string
  /** 波形列数 */
  columnCount: number
  /** 最大高度 */
  maxHeight: number
  /** 预览波形列 */
  columns: Array<PioneerPreviewWaveformColumn>
  /** 错误描述（失败时） */
  error?: string
}
/**
 * 计算音频文件的 SHA256 哈希值，并生成声纹与质量标签
 *
 * # 参数
 * * `file_paths` - 音频文件路径数组
 *
 * # 返回值
 * * 包含每个文件哈希值和路径的结果数组
 */
export declare function calculateAudioHashes(filePaths: Array<string>): Array<AudioFileResult>
/** 带进度回调的异步音频处理 */
export declare function calculateAudioHashesWithProgress(filePaths: Array<string>, callback?: (err: Error | null, arg: ProcessProgress) => any | undefined | null): Promise<Array<AudioFileResult>>
/** 计算整文件 SHA256（不解码，速度快；与 PCM 内容哈希互不兼容） */
export declare function calculateFileHashes(filePaths: Array<string>): Array<AudioFileResult>
/** 计算整文件 SHA256（带进度） */
export declare function calculateFileHashesWithProgress(filePaths: Array<string>, callback?: (err: Error | null, arg: ProcessProgress) => any | undefined | null): Promise<Array<AudioFileResult>>
/**
 * 解码音频文件为 PCM Float32Array
 *
 * # 参数
 * * `file_path` - 音频文件路径
 *
 * # 返回值
 * * 包含 PCM 数据和元数据的解码结果
 */
export declare function decodeAudioFile(filePath: string): DecodeAudioResult
/** 使用 SoundTouch 对交错 PCM 做不变调变速 */
export declare function processSoundtouchPcm(pcmData: Buffer, sampleRate: number, channels: number, tempoRatio: number): SoundTouchProcessResult
/** 基于 PCM 计算 Mixxx RGB 波形 */
export declare function computeMixxxWaveform(pcmData: Buffer, sampleRate: number, channels: number): MixxxWaveformData
/** 基于 PCM 计算 Mixxx RGB 波形（指定可视采样率） */
export declare function computeMixxxWaveformWithRate(pcmData: Buffer, sampleRate: number, channels: number, targetVisualRate: number): MixxxWaveformData
/** 基于 PCM 计算调性（Mixxx Queen Mary） */
export declare function analyzeKeyFromPcm(pcmData: Buffer, sampleRate: number, channels: number, fastAnalysis: boolean): KeyAnalysisResult
/**
 * 基于 PCM 同时计算调性与 BPM（Mixxx Queen Mary）
 *
 * # 参数
 * * `pcm_data` - 交错 PCM Buffer (f32 小端序)
 * * `sample_rate` - 采样率
 * * `channels` - 声道数
 * * `fast_analysis` - 是否启用 fast analysis
 */
export declare function analyzeKeyAndBpmFromPcm(pcmData: Buffer, sampleRate: number, channels: number, fastAnalysis: boolean): KeyBpmAnalysisResult
export declare function dumpPioneerExportDebug(exportPdbPath: string, maxRows?: number | undefined | null): PioneerExportDebugDump
export declare function readPioneerPlaylistTree(exportPdbPath: string): PioneerPlaylistTreeDump
export declare function readPioneerPreviewWaveform(analyzeFilePath: string): PioneerPreviewWaveformDump
export declare function readPioneerPlaylistTracks(exportPdbPath: string, playlistId: number, maxRows?: number | undefined | null): PioneerPlaylistTrackDump
