/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 进度信息结构体 */
export interface ProcessProgress {
  processed: number
  total: number
}
/** 音频文件处理结果 */
export interface AudioFileResult {
  sha256Hash: string
  filePath: string
}
/**
 * 计算音频文件的 SHA256 哈希值
 *
 * # 参数
 * * `file_paths` - 音频文件路径数组
 *
 * # 返回值
 * * 包含每个文件哈希值和路径的结果数组
 */
export declare function calculateAudioHashes(filePaths: Array<string>): Array<AudioFileResult>
/** 带进度回调的异步音频处理 */
export declare function calculateAudioHashesWithProgress(filePaths: Array<string>, callback?: (err: Error | null, arg: ProcessProgress) => any | undefined | null): Promise<Array<AudioFileResult>>
