export const HORIZONTAL_BROWSE_DETAIL_MIN_ZOOM = 20
export const HORIZONTAL_BROWSE_DETAIL_MAX_ZOOM = 180
export const HORIZONTAL_BROWSE_DETAIL_ZOOM_STEP_FACTOR = 1.08
export const HORIZONTAL_BROWSE_DETAIL_PLAYHEAD_RATIO = 0.5
export const HORIZONTAL_BROWSE_DETAIL_VISIBLE_DURATION_BASE_SEC = 240
