export const GAIN_ENVELOPE_MIN_GAP_RATIO = 0.004
export const GAIN_ENVELOPE_PERSIST_DEBOUNCE_MS = 180
export const GAIN_ENVELOPE_LOCKED_SEC_EPSILON = 0.0001
export const GAIN_ENVELOPE_SAME_SEC_EPSILON = 0.0001
export const GAIN_ENVELOPE_MAX_POINTS_PER_SEC = 2
export const VOLUME_MUTE_SEGMENT_EPSILON = 0.0001
export const MIX_PARAM_UNDO_STACK_LIMIT = 100
