import {
  LANE_COUNT,
  MIXTAPE_BASE_TRACK_LANE_HEIGHT,
  MIXTAPE_ENVELOPE_PREVIEW_BASE_LANE_HEIGHT,
  MIXTAPE_OVERVIEW_BASE_LANE_HEIGHT
} from '@renderer/composables/mixtape/constants'

export const TIMELINE_VISUAL_SCALE_MIN = 1
export const TIMELINE_VISUAL_SCALE_MAX = 3

const TIMELINE_TRACK_LANE_BORDER_PX = 2
const TIMELINE_TRACK_LANE_GAP_PX = 8
const TIMELINE_TRACK_VERTICAL_PADDING_PX = 20
const ENVELOPE_PREVIEW_LANE_GAP_PX = 2
const ENVELOPE_PREVIEW_LANE_PADDING_Y_PX = 2
const OVERVIEW_LANE_GAP_PX = 6
const OVERVIEW_LANE_PADDING_Y_PX = 8

const TRACK_SECTION_BASE_HEIGHT =
  LANE_COUNT * (MIXTAPE_BASE_TRACK_LANE_HEIGHT + TIMELINE_TRACK_LANE_BORDER_PX) +
  Math.max(0, LANE_COUNT - 1) * TIMELINE_TRACK_LANE_GAP_PX +
  TIMELINE_TRACK_VERTICAL_PADDING_PX
const ENVELOPE_SECTION_BASE_HEIGHT =
  LANE_COUNT * MIXTAPE_ENVELOPE_PREVIEW_BASE_LANE_HEIGHT +
  Math.max(0, LANE_COUNT - 1) * ENVELOPE_PREVIEW_LANE_GAP_PX +
  ENVELOPE_PREVIEW_LANE_PADDING_Y_PX
const OVERVIEW_SECTION_BASE_HEIGHT =
  LANE_COUNT * MIXTAPE_OVERVIEW_BASE_LANE_HEIGHT +
  Math.max(0, LANE_COUNT - 1) * OVERVIEW_LANE_GAP_PX +
  OVERVIEW_LANE_PADDING_Y_PX

export const resolveTimelineScalableBaseHeightByTrackCount = (trackCount: number) => {
  const hasTracks = Number(trackCount) > 0
  const envelopeSectionHeight = hasTracks ? ENVELOPE_SECTION_BASE_HEIGHT : 0
  return Math.max(
    1,
    TRACK_SECTION_BASE_HEIGHT + envelopeSectionHeight + OVERVIEW_SECTION_BASE_HEIGHT
  )
}
