from pathlib import Path
from typing import Any

from rkb_dataset_contract import sha256_file


def build_usable_grid_cli_payload(
    *,
    python: str,
    feature_script: Path,
    benchmark_script: Path,
    multiscale_script: Path,
    candidate_eval_script: Path,
    candidate_path: Path,
    truth: Path,
    audio: Path,
    batch: Path,
    args: Any,
) -> dict[str, Any]:
    feature_cache = batch / "feature-cache"
    multiscale_cache = batch / "multiscale-feature-cache"
    work = batch / "work"
    common = {
        "python": python,
        "device": str(args.device),
        "jobs": int(args.jobs),
        "predictionCacheDir": str(Path(args.prediction_cache_dir).resolve()),
        "ffmpeg": str(Path(args.ffmpeg).resolve()),
        "ffprobe": str(Path(args.ffprobe).resolve()),
    }
    return {
        **common,
        "artifacts": {
            "candidatePath": str(candidate_path.resolve()),
            "candidateFileSha256": sha256_file(candidate_path),
        },
        "featureCache": [
            python,
            str(feature_script),
            "--truth",
            str(truth),
            "--truth-batch-id",
            batch.name,
            "--registry",
            str(Path(args.registry).resolve()),
            "--audio-root",
            str(audio),
            "--ffmpeg",
            common["ffmpeg"],
            "--ffprobe",
            common["ffprobe"],
            "--cache-dir",
            str(feature_cache),
            "--prediction-cache-dir",
            common["predictionCacheDir"],
            "--device",
            common["device"],
            "--jobs",
            str(common["jobs"]),
            "--shard-dir",
            str(work / "feature-cache-shards"),
            "--keep-shards",
        ],
        "baselineBenchmarkTemplate": [
            python,
            str(benchmark_script),
            "--truth",
            str(truth),
            "--truth-batch-id",
            batch.name,
            "--registry",
            str(Path(args.registry).resolve()),
            "--audio-root",
            str(audio),
            "--ffmpeg",
            common["ffmpeg"],
            "--ffprobe",
            common["ffprobe"],
            "--output",
            "{baselineOutput}",
            "--solver",
            "constant-grid-dp",
            "--feature-cache-dir",
            str(feature_cache),
            "--prediction-cache-dir",
            common["predictionCacheDir"],
            "--device",
            common["device"],
            "--jobs",
            str(common["jobs"]),
            "--shard-dir",
            str(work / "benchmark-shards"),
            "--progress-output",
            str(work / "benchmark-progress.json"),
            "--keep-shards",
        ],
        "multiscaleFeatureCache": [
            python,
            str(multiscale_script),
            "--source-cache-dir",
            str(feature_cache),
            "--output-cache-dir",
            str(multiscale_cache),
            "--ffmpeg",
            common["ffmpeg"],
            "--workers",
            str(max(1, min(4, int(common["jobs"])))),
        ],
        "candidateEvaluationTemplate": [
            python,
            str(candidate_eval_script),
            "--truth",
            str(truth),
            "--truth-batch-id",
            batch.name,
            "--baseline-benchmark",
            "{baselineOutput}",
            "--source-cache-dir",
            str(feature_cache),
            "--multiscale-cache-dir",
            str(multiscale_cache),
            "--row-cache-dir",
            str(work / "usable-grid-row-cache"),
            "--candidate",
            str(candidate_path),
            "--output",
            "{attemptOutput}",
        ],
    }
