/* tslint:disable */
 

/* auto-generated by NAPI-RS */

/** 进度信息结构体 */
export interface ProcessProgress {
  processed: number
  total: number
}
/** 音频文件处理结果 */
export interface AudioFileResult {
  /** 整个文件的 SHA256（当前为标准化 PCM 内容哈希），用于去重 */
  sha256Hash: string
  /** 原始文件路径 */
  filePath: string
  /** 错误描述（当分析失败时） */
  error?: string
}
/** 音频解码结果 */
export interface DecodeAudioResult {
  /** PCM 数据（Buffer，内部为 f32 小端序，需在 JS 侧转为 Float32Array） */
  pcmData: Buffer
  /** 采样率 */
  sampleRate: number
  /** 声道数 */
  channels: number
  /** 总帧数 */
  totalFrames: number
  /** 错误描述（当解码失败时） */
  error?: string
}
/** 调性分析结果 */
export interface KeyAnalysisResult {
  /** ID3v2 ASCII key 文本 */
  keyText: string
  /** 错误描述（当分析失败时） */
  error?: string
}
/** 调性+BPM分析结果 */
export interface KeyBpmAnalysisResult {
  /** ID3v2 ASCII key 文本 */
  keyText: string
  /** BPM 值 */
  bpm: number
  /** 首拍偏移（毫秒） */
  firstBeatMs: number
  /** 调性分析错误描述 */
  keyError?: string
  /** BPM 分析错误描述 */
  bpmError?: string
}
/** Mixxx 波形频段数据 */
export interface MixxxWaveformBand {
  left: Buffer
  right: Buffer
  peakLeft: Buffer
  peakRight: Buffer
}
/** Mixxx 波形三频数据 */
export interface MixxxWaveformBands {
  low: MixxxWaveformBand
  mid: MixxxWaveformBand
  high: MixxxWaveformBand
}
/** Mixxx 波形数据 */
export interface MixxxWaveformData {
  duration: number
  sampleRate: number
  step: number
  bands: MixxxWaveformBands
}
/**
 * 计算音频文件的 SHA256 哈希值，并生成声纹与质量标签
 *
 * # 参数
 * * `file_paths` - 音频文件路径数组
 *
 * # 返回值
 * * 包含每个文件哈希值和路径的结果数组
 */
export declare function calculateAudioHashes(filePaths: Array<string>): Array<AudioFileResult>
/** 带进度回调的异步音频处理 */
export declare function calculateAudioHashesWithProgress(
  filePaths: Array<string>,
  callback?: (err: Error | null, arg: ProcessProgress) => any | undefined | null
): Promise<Array<AudioFileResult>>
/** 计算整文件 SHA256（不解码，速度快；与 PCM 内容哈希互不兼容） */
export declare function calculateFileHashes(filePaths: Array<string>): Array<AudioFileResult>
/** 计算整文件 SHA256（带进度） */
export declare function calculateFileHashesWithProgress(
  filePaths: Array<string>,
  callback?: (err: Error | null, arg: ProcessProgress) => any | undefined | null
): Promise<Array<AudioFileResult>>
/**
 * 解码音频文件为 PCM Float32Array
 *
 * # 参数
 * * `file_path` - 音频文件路径
 *
 * # 返回值
 * * 包含 PCM 数据和元数据的解码结果
 */
export declare function decodeAudioFile(filePath: string): DecodeAudioResult
/**
 * 基于 PCM 计算 Mixxx RGB 波形
 *
 * # 参数
 * * `pcm_data` - 交错 PCM Buffer (f32 小端序)
 * * `sample_rate` - 采样率
 * * `channels` - 声道数
 */
export declare function computeMixxxWaveform(
  pcmData: Buffer,
  sampleRate: number,
  channels: number
): MixxxWaveformData
/**
 * 基于 PCM 计算调性（Mixxx Queen Mary）
 *
 * # 参数
 * * `pcm_data` - 交错 PCM Buffer (f32 小端序)
 * * `sample_rate` - 采样率
 * * `channels` - 声道数
 * * `fast_analysis` - 是否启用 fast analysis
 */
export declare function analyzeKeyFromPcm(
  pcmData: Buffer,
  sampleRate: number,
  channels: number,
  fastAnalysis: boolean
): KeyAnalysisResult
/**
 * 基于 PCM 同时计算调性与 BPM（Mixxx Queen Mary）
 *
 * # 参数
 * * `pcm_data` - 交错 PCM Buffer (f32 小端序)
 * * `sample_rate` - 采样率
 * * `channels` - 声道数
 * * `fast_analysis` - 是否启用 fast analysis
 */
export declare function analyzeKeyAndBpmFromPcm(
  pcmData: Buffer,
  sampleRate: number,
  channels: number,
  fastAnalysis: boolean
): KeyBpmAnalysisResult

export {}
